name: Web FIK Frontend

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm test
      - run: npm run build --if-present
      - name: Create Failed Test Status Check
        if: ${{ failure() }}
        uses: actions/github-script@v5
        with:
          script: |
            const { owner, repo, number } = context.issue;
            const { data: { head: { sha } } } = await github.pulls.get({ owner, repo, pull_number: number });
            await github.repos.createCommitStatus({
              owner,
              repo,
              sha,
              state: 'failure',
              context: 'Test',
              description: 'Tests failed',
            });
